resilience4j.retry:
           instances:
             sample-api:
                 maxAttempts: 7
                 waitDuration: 10s
                 retryExceptions:
                      - org.springframework.web.client.HttpServerErrorException
